<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Triage de reportes de incidentes viales del C5 (CDMX 2022-2024) – Triage de reportes viales del C5</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-2f125ff416301e0bbe8ba1891721f241.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Triage de reportes viales del C5</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../notebooks/01_eda.html" aria-current="page"> 
<span class="menu-text">01 · EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notebooks/02_clasificacion.html"> 
<span class="menu-text">02 · Clasificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notebooks/03_clustering.html"> 
<span class="menu-text">03 · Clustering</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../mapa.html"> 
<span class="menu-text">🗺️ Mapa interactivo</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../instalacion.html"> 
<span class="menu-text">Instalación</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#notebook-01---analisis-exploratorio-de-datos-eda" id="toc-notebook-01---analisis-exploratorio-de-datos-eda" class="nav-link active" data-scroll-target="#notebook-01---analisis-exploratorio-de-datos-eda">Notebook 01 - Analisis Exploratorio de Datos (EDA)</a>
  <ul class="collapse">
  <li><a href="#el-problema-triage-de-veracidad-de-reportes-viales" id="toc-el-problema-triage-de-veracidad-de-reportes-viales" class="nav-link" data-scroll-target="#el-problema-triage-de-veracidad-de-reportes-viales">El problema: triage de veracidad de reportes viales</a></li>
  </ul></li>
  <li><a href="#configuracion" id="toc-configuracion" class="nav-link" data-scroll-target="#configuracion">0. Configuracion</a></li>
  <li><a href="#diccionario-de-datos" id="toc-diccionario-de-datos" class="nav-link" data-scroll-target="#diccionario-de-datos">1. Diccionario de datos</a>
  <ul class="collapse">
  <li><a href="#respaldo-empirico-del-diccionario" id="toc-respaldo-empirico-del-diccionario" class="nav-link" data-scroll-target="#respaldo-empirico-del-diccionario">1.1 Respaldo empirico del diccionario</a></li>
  </ul></li>
  <li><a href="#preparacion-de-datos" id="toc-preparacion-de-datos" class="nav-link" data-scroll-target="#preparacion-de-datos">2. Preparacion de datos</a>
  <ul class="collapse">
  <li><a href="#analisis-de-codigo_cierre-por-que-eliminamos-los-duplicados" id="toc-analisis-de-codigo_cierre-por-que-eliminamos-los-duplicados" class="nav-link" data-scroll-target="#analisis-de-codigo_cierre-por-que-eliminamos-los-duplicados">2.1 Analisis de <code>codigo_cierre</code>: por que eliminamos los duplicados</a></li>
  <li><a href="#la-clase-pipelinepreparacion-y-los-pasos" id="toc-la-clase-pipelinepreparacion-y-los-pasos" class="nav-link" data-scroll-target="#la-clase-pipelinepreparacion-y-los-pasos">2.2 La clase <code>PipelinePreparacion</code> y los pasos</a></li>
  <li><a href="#calidad-de-los-datos-faltantes-y-duplicados" id="toc-calidad-de-los-datos-faltantes-y-duplicados" class="nav-link" data-scroll-target="#calidad-de-los-datos-faltantes-y-duplicados">3.1 Calidad de los datos: faltantes y duplicados</a></li>
  <li><a href="#estadistica-descriptiva-hora-y-tiempo_cierre_min" id="toc-estadistica-descriptiva-hora-y-tiempo_cierre_min" class="nav-link" data-scroll-target="#estadistica-descriptiva-hora-y-tiempo_cierre_min">3.2 Estadistica descriptiva: <code>HORA</code> y <code>TIEMPO_CIERRE_MIN</code></a></li>
  <li><a href="#valores-atipicos-en-tiempo_cierre_min-boxplot-regla-iqr" id="toc-valores-atipicos-en-tiempo_cierre_min-boxplot-regla-iqr" class="nav-link" data-scroll-target="#valores-atipicos-en-tiempo_cierre_min-boxplot-regla-iqr">3.3 Valores atipicos en <code>TIEMPO_CIERRE_MIN</code> (boxplot + regla IQR)</a></li>
  <li><a href="#distribuciones-hora-franja-y-dia_semana" id="toc-distribuciones-hora-franja-y-dia_semana" class="nav-link" data-scroll-target="#distribuciones-hora-franja-y-dia_semana">3.4 Distribuciones: <code>HORA</code>, <code>FRANJA</code> y <code>dia_semana</code></a></li>
  <li><a href="#balance-del-target-real-decision-de-diseno" id="toc-balance-del-target-real-decision-de-diseno" class="nav-link" data-scroll-target="#balance-del-target-real-decision-de-diseno">3.5 Balance del target <code>REAL</code> (decision de diseno)</a></li>
  <li><a href="#correlaciones-entre-numericas-y-dispersion-espacial" id="toc-correlaciones-entre-numericas-y-dispersion-espacial" class="nav-link" data-scroll-target="#correlaciones-entre-numericas-y-dispersion-espacial">3.6 Correlaciones entre numericas y dispersion espacial</a></li>
  </ul></li>
  <li><a href="#geografia-del-reporte-quien-reporta-donde-y-que-tan-confiable-es" id="toc-geografia-del-reporte-quien-reporta-donde-y-que-tan-confiable-es" class="nav-link" data-scroll-target="#geografia-del-reporte-quien-reporta-donde-y-que-tan-confiable-es">4. Geografia del reporte: ¿quien reporta, donde y que tan confiable es?</a>
  <ul class="collapse">
  <li><a href="#confiabilidad-por-canal-de-entrada-tipo_entrada" id="toc-confiabilidad-por-canal-de-entrada-tipo_entrada" class="nav-link" data-scroll-target="#confiabilidad-por-canal-de-entrada-tipo_entrada">4.1 Confiabilidad por canal de entrada (<code>tipo_entrada</code>)</a></li>
  <li><a href="#confiabilidad-por-alcaldia" id="toc-confiabilidad-por-alcaldia" class="nav-link" data-scroll-target="#confiabilidad-por-alcaldia">4.2 Confiabilidad por alcaldia</a></li>
  <li><a href="#mezcla-canal-x-alcaldia-heatmap-y-prueba-de-independencia" id="toc-mezcla-canal-x-alcaldia-heatmap-y-prueba-de-independencia" class="nav-link" data-scroll-target="#mezcla-canal-x-alcaldia-heatmap-y-prueba-de-independencia">4.3 Mezcla canal x alcaldia: heatmap y prueba de independencia</a></li>
  <li><a href="#canal-x-franja-horaria" id="toc-canal-x-franja-horaria" class="nav-link" data-scroll-target="#canal-x-franja-horaria">4.4 Canal x franja horaria</a></li>
  <li><a href="#confiabilidad-por-franja-horaria" id="toc-confiabilidad-por-franja-horaria" class="nav-link" data-scroll-target="#confiabilidad-por-franja-horaria">4.5 Confiabilidad por franja horaria</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Triage de reportes de incidentes viales del C5 (CDMX 2022-2024)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Proyecto Final - Almacenes y Mineria de Datos</strong></p>
<p><strong>Profesora:</strong> Jessica Santizo Galicia <strong>Ayudantes:</strong> Diego Antonio Villalba Gonzalez y Ares Gael Castro Romero <strong>Integrante:</strong> Jose Ruben Alfaro Gonzalez — No.&nbsp;de cuenta: 320516436 <strong>Fecha:</strong> 10-06-2026</p>
<hr>
<section id="notebook-01---analisis-exploratorio-de-datos-eda" class="level2">
<h2 class="anchored" data-anchor-id="notebook-01---analisis-exploratorio-de-datos-eda">Notebook 01 - Analisis Exploratorio de Datos (EDA)</h2>
<section id="el-problema-triage-de-veracidad-de-reportes-viales" class="level3">
<h3 class="anchored" data-anchor-id="el-problema-triage-de-veracidad-de-reportes-viales">El problema: triage de veracidad de reportes viales</h3>
<p>El <strong>Centro de Comando, Control, Computo, Comunicaciones y Contacto Ciudadano (C5)</strong> de la Ciudad de Mexico recibe cientos de miles de reportes de incidentes viales al año. Una fracción grande de esos reportes resulta ser <strong>falsa</strong> o simplemente <strong>informativa</strong>. Alguien llama por un choque que ya se resolvió, una cámara detecta un vehículo que en realidad estaba estacionado, etc. Despachar unidades de emergencia hacia reportes que no son reales <strong>desperdicia recursos</strong> y resta capacidad de respuesta a las emergencias verdaderas.</p>
<p>Este cuaderno explora los datos para entender que información, <strong>disponible en el momento en que entra el reporte</strong> (hora, tipo de incidente, fuente, alcaldía, ubicación), permitiendo así anticipar si un reporte se confirmara como <strong>real</strong> el actuar de las autoridades. Esa es la pregunta del <strong>target</strong>:</p>
<blockquote class="blockquote">
<p><strong><code>REAL = 1</code></strong> si el reporte es real (cierre afirmativo, <code>codigo_cierre == 'A'</code>), <strong><code>REAL = 0</code></strong> si es falso (<code>F</code>) o informativo (<code>I</code>).</p>
</blockquote>
<p>La semilla <code>42</code> se fija para todo muestreo reproducible.</p>
<blockquote class="blockquote">
<p><strong>Frontera anti-fuga.</strong> Las columnas que solo se conocen <em>al cerrar</em> el reporte (<code>codigo_cierre</code>, <code>CIERRE_DESC</code>, <code>TIEMPO_CIERRE_MIN</code>) y <code>clas_con_f_alarma</code> (su categoria <em>FALSA ALARMA</em> es una clasificacion posterior) se usan <strong>solo para EDA</strong> y nunca como variables del modelo.</p>
</blockquote>
</section>
</section>
<section id="configuracion" class="level2">
<h2 class="anchored" data-anchor-id="configuracion">0. Configuracion</h2>
<p>Primero, importamos librerias, fijamos la semilla y resolvemos las rutas a <code>data/</code> con <code>pathlib</code>, relativas a la ubicacion del notebook (<code>notebooks/</code>), para que el cuaderno corra sin importar el directorio de trabajo.</p>
<div id="fc57dfd0" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:50.919914Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:50.919667Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.156715Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.156525Z&quot;}}" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>SEMILLA <span class="op">=</span> <span class="dv">42</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>np.random.seed(SEMILLA)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"figure.dpi"</span>] <span class="op">=</span> <span class="dv">110</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">"display.max_columns"</span>, <span class="dv">50</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Rutas relativas a la ubicacion del notebook (carpeta notebooks/).</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>BASE <span class="op">=</span> Path.cwd() <span class="cf">if</span> (Path.cwd() <span class="op">/</span> <span class="st">"data"</span>).exists() <span class="cf">else</span> Path.cwd().parent</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>DATA <span class="op">=</span> BASE <span class="op">/</span> <span class="st">"data"</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>FIGURES <span class="op">=</span> BASE <span class="op">/</span> <span class="st">"figures"</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>REPORTS <span class="op">=</span> BASE <span class="op">/</span> <span class="st">"reports"</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>FIGURES.mkdir(exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>REPORTS.mkdir(exist_ok<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co"># El codigo fuente vive en src/ (clases y modulos). Lo importamos:</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">str</span>(BASE) <span class="kw">not</span> <span class="kw">in</span> sys.path:</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    sys.path.insert(<span class="dv">0</span>, <span class="bu">str</span>(BASE))</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.preparacion <span class="im">import</span> PipelinePreparacion, pipeline_estandar</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.viz <span class="im">import</span> barras, guardar, resumen_numerico</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"BASE   :"</span>, BASE)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"DATA   :"</span>, DATA)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Semilla:"</span>, SEMILLA)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BASE   : /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM
DATA   : /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/data
Semilla: 42</code></pre>
</div>
</div>
</section>
<section id="diccionario-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="diccionario-de-datos">1. Diccionario de datos</h2>
<p>A continuación presentamos el diccionario de variables. Este también se encuentra en <code>reports/diccionario_datos.md</code>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Tipo</th>
<th>Significado</th>
<th>Valores posibles / rango</th>
<th>Rol</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>folio</code></td>
<td>texto (id)</td>
<td>Identificador unico del reporte.</td>
<td>Cadena tipo <code>C2C/20211229/00212</code>.</td>
<td>id (no feature)</td>
</tr>
<tr class="even">
<td><code>FECHA_CREACION</code></td>
<td>datetime</td>
<td>Fecha-hora de creacion del reporte.</td>
<td>2022-01 a 2024-02 (tras depurar).</td>
<td>excluida (id temporal)</td>
</tr>
<tr class="odd">
<td><code>codigo_cierre</code></td>
<td>categorica</td>
<td>Como cerro el reporte. Base del target.</td>
<td><code>A</code>=Afirmativo (real), <code>D</code>=Duplicado (real, ya reportado), <code>F</code>=Falso, <code>I</code>=Informativo.</td>
<td>excluida (base del target)</td>
</tr>
<tr class="even">
<td><code>CIERRE_DESC</code></td>
<td>texto</td>
<td>Descripcion legible de <code>codigo_cierre</code>.</td>
<td>Texto libre por codigo.</td>
<td>excluida (id/descriptivo)</td>
</tr>
<tr class="odd">
<td><code>REAL</code></td>
<td>entero 0/1</td>
<td><strong>TARGET.</strong> ¿El reporte es real (afirmativo)?</td>
<td><code>1</code> si <code>codigo_cierre=='A'</code>; <code>0</code> si <code>F</code>/<code>I</code>. Definido tras eliminar <code>D</code>.</td>
<td><strong>target</strong></td>
</tr>
<tr class="even">
<td><code>HORA</code></td>
<td>entero</td>
<td>Hora del dia del reporte.</td>
<td>0-23.</td>
<td>feature (numerica)</td>
</tr>
<tr class="odd">
<td><code>MES</code></td>
<td>entero</td>
<td>Mes del reporte.</td>
<td>1-12.</td>
<td>feature (numerica)</td>
</tr>
<tr class="even">
<td><code>ANIO</code></td>
<td>entero</td>
<td>Ano del reporte.</td>
<td>2022-2024.</td>
<td>feature (numerica)</td>
</tr>
<tr class="odd">
<td><code>latitud</code></td>
<td>float</td>
<td>Latitud del incidente (CDMX).</td>
<td>~19.09 - 19.63.</td>
<td>feature (numerica / clustering)</td>
</tr>
<tr class="even">
<td><code>longitud</code></td>
<td>float</td>
<td>Longitud del incidente (CDMX).</td>
<td>~ -99.35 - -98.95.</td>
<td>feature (numerica / clustering)</td>
</tr>
<tr class="odd">
<td><code>tipo_incidente_c4</code></td>
<td>categorica (7)</td>
<td>Tipo grueso de incidente.</td>
<td>Accidente, Lesionado, Cadaver, Detencion ciudadana, Mi Calle, Sismo, Mi Taxi.</td>
<td>feature</td>
</tr>
<tr class="even">
<td><code>incidente_c4</code></td>
<td>categorica (16)</td>
<td>Subtipo detallado del incidente.</td>
<td>Choque sin/con lesionados, Atropellado, Motociclista, Volcadura, Ciclista, Persona atrapada/desbarrancada, Vehiculo atrapado/varado, Choque con prensados, Accidente automovilistico, Incidente de transito, Vehiculo desbarrancado, Otros, Monopatin, Ferroviario, Persona atropellada.</td>
<td>feature</td>
</tr>
<tr class="odd">
<td><code>tipo_entrada</code></td>
<td>categorica (~9)</td>
<td>Canal por el que entro el reporte.</td>
<td>LLAMADA DEL 911 (mayoria), BOTON DE AUXILIO, RADIO, CAMARA, REDES, APLICATIVOS, LLAMADA APP911, SOS MUJERES *765, LECTOR DE PLACAS. (3 nulos.)</td>
<td>feature</td>
</tr>
<tr class="even">
<td><code>alcaldia_catalogo</code></td>
<td>categorica (16)</td>
<td>Alcaldia de CDMX del incidente.</td>
<td>Las 16 alcaldias (Iztapalapa, Gustavo A. Madero, Cuauhtemoc, … Milpa Alta). (366 nulos.)</td>
<td>feature</td>
</tr>
<tr class="odd">
<td><code>dia_semana</code></td>
<td>categorica (7)</td>
<td>Dia de la semana del reporte.</td>
<td>Lunes…Domingo.</td>
<td>feature</td>
</tr>
<tr class="even">
<td><code>FRANJA</code></td>
<td>categorica (4)</td>
<td>Franja horaria (derivada de <code>HORA</code>).</td>
<td>Madrugada, Mañana, Tarde, Noche.</td>
<td>feature</td>
</tr>
<tr class="odd">
<td><code>clas_con_f_alarma</code></td>
<td>categorica</td>
<td>Clasificacion operativa (con falsa alarma).</td>
<td>URGENCIAS MEDICAS, EMERGENCIA, DELITO, FALSA ALARMA, INCIDENTES EXTERNOS.</td>
<td>excluida (fuga fina)</td>
</tr>
<tr class="even">
<td><code>TIEMPO_CIERRE_MIN</code></td>
<td>float (min)</td>
<td>Tiempo hasta cerrar el reporte.</td>
<td>Minutos &gt; 0 (2 nulos).</td>
<td>excluida (fuga gruesa)</td>
</tr>
</tbody>
</table>
<p><strong>Decisiones de rol clave:</strong> El target <code>REAL</code> se define <strong>tras eliminar los duplicados</strong> <code>D</code> (lo justificamos en la seccion 2). Además, <code>clas_con_f_alarma</code> y <code>TIEMPO_CIERRE_MIN</code> se <strong>excluyen del modelo por fuga</strong>, pues la primera es una clasificacion posterior al cierre (su categoria <em>FALSA ALARMA</em> delata el desenlace) y la segunda solo se conoce cuando el reporte ya cerro. <code>folio</code>, <code>FECHA_CREACION</code>, <code>codigo_cierre</code> y <code>CIERRE_DESC</code> son identificadores o la base del target.</p>
<section id="respaldo-empirico-del-diccionario" class="level3">
<h3 class="anchored" data-anchor-id="respaldo-empirico-del-diccionario">1.1 Respaldo empirico del diccionario</h3>
<p>Verificamos los tipos reales de cada columna y los valores efectivos de las categoricas clave y las numericas. Cargamos directamente el dataset de trabajo ya depurado <code>c5_listo.parquet</code>.</p>
<div id="aa624156" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.157835Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.157743Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.263826Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.263634Z&quot;}}" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_parquet(DATA <span class="op">/</span> <span class="st">"c5_listo.parquet"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Dimensiones del dataset de trabajo (c5_listo):"</span>, df.shape)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Tipos por variable (respaldo del diccionario).</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df.dtypes.astype(<span class="bu">str</span>).rename(<span class="st">"dtype"</span>).to_frame()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensiones del dataset de trabajo (c5_listo): (289885, 18)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">dtype</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">folio</th>
<td>string</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">REAL</th>
<td>int8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">CIERRE_DESC</th>
<td>str</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">codigo_cierre</th>
<td>string</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">HORA</th>
<td>int16</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">MES</th>
<td>int16</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">ANIO</th>
<td>int16</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">latitud</th>
<td>Float64</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">longitud</th>
<td>Float64</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">tipo_incidente_c4</th>
<td>str</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">incidente_c4</th>
<td>str</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">tipo_entrada</th>
<td>str</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">alcaldia_catalogo</th>
<td>str</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">dia_semana</th>
<td>str</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">FRANJA</th>
<td>str</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">clas_con_f_alarma</th>
<td>str</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">TIEMPO_CIERRE_MIN</th>
<td>float64</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">FECHA_CREACION</th>
<td>datetime64[us]</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="462df268" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.264846Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.264782Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.290881Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.290673Z&quot;}}" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores reales de las categoricas clave (respaldo de "valores posibles").</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> [<span class="st">"codigo_cierre"</span>, <span class="st">"tipo_incidente_c4"</span>, <span class="st">"tipo_entrada"</span>, <span class="st">"FRANJA"</span>, <span class="st">"dia_semana"</span>]:</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">### </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">  (</span><span class="sc">{</span>df[col]<span class="sc">.</span>nunique(dropna<span class="op">=</span><span class="va">True</span>)<span class="sc">}</span><span class="ss"> categorias)"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(df[col].value_counts(dropna<span class="op">=</span><span class="va">False</span>).head(<span class="dv">12</span>).to_string())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
### codigo_cierre  (3 categorias)
codigo_cierre
A    184067
F    102211
I      3607

### tipo_incidente_c4  (7 categorias)
tipo_incidente_c4
Accidente              262447
Lesionado               25848
Cadáver                  1052
Mi Calle                  307
Detención ciudadana       122
Mi Taxi                    56
Sismo                      53

### tipo_entrada  (9 categorias)
tipo_entrada
LLAMADA DEL 911     253917
RADIO                19541
BOTÓN DE AUXILIO     14256
CÁMARA                1188
APLICATIVOS            504
REDES                  438
LLAMADA APP911          35
NaN                      3
SOS MUJERES *765         2
LECTOR DE PLACAS         1

### FRANJA  (4 categorias)
FRANJA
Noche        97325
Tarde        95820
Mañana       66177
Madrugada    30563

### dia_semana  (7 categorias)
dia_semana
Viernes      46428
Sábado       46329
Jueves       40381
Miércoles    39903
Domingo      39682
Martes       39468
Lunes        37694</code></pre>
</div>
</div>
<div id="33e6afa7" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.291853Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.291802Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.319992Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.319827Z&quot;}}" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rango/estadistica de las numericas (respaldo de "rango").</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">"HORA"</span>, <span class="st">"MES"</span>, <span class="st">"ANIO"</span>, <span class="st">"latitud"</span>, <span class="st">"longitud"</span>, <span class="st">"TIEMPO_CIERRE_MIN"</span>]].describe().T</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">HORA</th>
<td>289885.0</td>
<td>13.850441</td>
<td>6.084333</td>
<td>0.0</td>
<td>9.0</td>
<td>15.0</td>
<td>19.0</td>
<td>23.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">MES</th>
<td>289885.0</td>
<td>6.369547</td>
<td>3.58989</td>
<td>1.0</td>
<td>3.0</td>
<td>6.0</td>
<td>10.0</td>
<td>12.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">ANIO</th>
<td>289885.0</td>
<td>2022.6167</td>
<td>0.619983</td>
<td>2022.0</td>
<td>2022.0</td>
<td>2023.0</td>
<td>2023.0</td>
<td>2024.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">latitud</th>
<td>289885.0</td>
<td>19.381961</td>
<td>0.071024</td>
<td>19.094877</td>
<td>19.333475</td>
<td>19.38364</td>
<td>19.43398</td>
<td>19.632201</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">longitud</th>
<td>289885.0</td>
<td>-99.134408</td>
<td>0.062507</td>
<td>-99.35257</td>
<td>-99.17557</td>
<td>-99.137497</td>
<td>-99.092705</td>
<td>-98.94639</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">TIEMPO_CIERRE_MIN</th>
<td>289883.0</td>
<td>296.862295</td>
<td>340.365014</td>
<td>0.316667</td>
<td>184.7</td>
<td>188.783333</td>
<td>225.8</td>
<td>4657.133333</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="41cfe03a" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.320920Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.320871Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.323699Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.323540Z&quot;}}" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Escribimos el mismo diccionario a reports/diccionario_datos.md (tabla markdown).</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>diccionario_md <span class="op">=</span> <span class="st">"""# Diccionario de datos - C5 incidentes viales (CDMX 2022-2024)</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="st">**Proyecto Final - Almacenes y Mineria de Datos.** Profesora: Jessica Santizo Galicia.</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="st">Ayudantes: Diego Antonio Villalba Gonzalez y Ares Gael Castro Romero. Fecha: 2026-06.</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="st">Documenta cada variable, su significado, los valores que puede tomar y su rol</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="st">(target / feature / excluida / id). Dataset de trabajo: data/c5_listo.parquet</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="st">(289,885 filas, sin duplicados y sin el ano-ruido 2021).</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="st">| Variable | Tipo | Significado | Valores posibles / rango | Rol |</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="st">|---|---|---|---|---|</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="st">| `folio` | texto (id) | Identificador unico del reporte. | Cadena tipo C2C/20211229/00212. | id (no feature) |</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a><span class="st">| `FECHA_CREACION` | datetime | Fecha-hora de creacion del reporte. | 2022-01 a 2024-02 (tras depurar). | excluida (id temporal) |</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="st">| `codigo_cierre` | categorica | Como cerro el reporte. Base del target. | A=Afirmativo (real), D=Duplicado (real, ya reportado), F=Falso, I=Informativo. | excluida (base del target) |</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="st">| `CIERRE_DESC` | texto | Descripcion legible de codigo_cierre. | Texto libre por codigo. | excluida (descriptivo) |</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="st">| `REAL` | entero 0/1 | TARGET: el reporte es real (afirmativo)? | 1 si codigo_cierre=='A'; 0 si F/I. Definido tras quitar D. | target |</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="st">| `HORA` | entero | Hora del dia del reporte. | 0-23. | feature (num) |</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="st">| `MES` | entero | Mes del reporte. | 1-12. | feature (num) |</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="st">| `ANIO` | entero | Ano del reporte. | 2022-2024. | feature (num) |</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="st">| `latitud` | float | Latitud del incidente (CDMX). | ~19.09-19.63. | feature (num / clustering) |</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="st">| `longitud` | float | Longitud del incidente (CDMX). | ~-99.35 a -98.95. | feature (num / clustering) |</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="st">| `tipo_incidente_c4` | cat (7) | Tipo grueso de incidente. | Accidente, Lesionado, Cadaver, Detencion ciudadana, Mi Calle, Sismo, Mi Taxi. | feature |</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="st">| `incidente_c4` | cat (16) | Subtipo detallado del incidente. | Choque sin/con lesionados, Atropellado, Motociclista, Volcadura, Ciclista, Persona atrapada/desbarrancada, Vehiculo atrapado/varado, Choque con prensados, Accidente automovilistico, Incidente de transito, Vehiculo desbarrancado, Otros, Monopatin, Ferroviario, Persona atropellada. | feature |</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a><span class="st">| `tipo_entrada` | cat (~9) | Canal por el que entro el reporte. | LLAMADA DEL 911 (mayoria), BOTON DE AUXILIO, RADIO, CAMARA, REDES, APLICATIVOS, LLAMADA APP911, SOS MUJERES *765, LECTOR DE PLACAS. (3 nulos.) | feature |</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="st">| `alcaldia_catalogo` | cat (16) | Alcaldia de CDMX del incidente. | Las 16 alcaldias (Iztapalapa, Gustavo A. Madero, Cuauhtemoc, ... Milpa Alta). (366 nulos.) | feature |</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a><span class="st">| `dia_semana` | cat (7) | Dia de la semana del reporte. | Lunes...Domingo. | feature |</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="st">| `FRANJA` | cat (4) | Franja horaria (derivada de HORA). | Madrugada, Mañana, Tarde, Noche. | feature |</span></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="st">| `clas_con_f_alarma` | categorica | Clasificacion operativa (con falsa alarma). | URGENCIAS MEDICAS, EMERGENCIA, DELITO, FALSA ALARMA, INCIDENTES EXTERNOS. | excluida (fuga fina) |</span></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a><span class="st">| `TIEMPO_CIERRE_MIN` | float (min) | Tiempo hasta cerrar el reporte. | Minutos &gt; 0 (2 nulos). | excluida (fuga gruesa) |</span></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a><span class="st">## Notas de rol</span></span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a><span class="st">- TARGET (REAL): se define tras ELIMINAR los duplicados D. Un cierre D es un evento real</span></span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a><span class="st">  ya reportado; su deduplicacion es tarea del sistema de despacho, no del modelo de</span></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a><span class="st">  veracidad. Entre el resto, REAL=1 si 'A' (afirmativo), 0 si 'F'/'I'.</span></span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a><span class="st">- Excluidas por fuga: clas_con_f_alarma (fuga fina: 'FALSA ALARMA' es clasificacion</span></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a><span class="st">  posterior al cierre) y TIEMPO_CIERRE_MIN (fuga gruesa: solo se conoce al cerrar).</span></span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a><span class="st">- Excluidas por ser id o base del target: folio, FECHA_CREACION, codigo_cierre, CIERRE_DESC.</span></span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a><span class="st">## Features del modelo</span></span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a><span class="st">- Numericas: HORA, MES, ANIO, latitud, longitud.</span></span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a><span class="st">- Categoricas: tipo_incidente_c4, incidente_c4, tipo_entrada, alcaldia_catalogo, dia_semana, FRANJA.</span></span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span></span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>(REPORTS <span class="op">/</span> <span class="st">"diccionario_datos.md"</span>).write_text(diccionario_md, encoding<span class="op">=</span><span class="st">"utf-8"</span>)</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Diccionario escrito en:"</span>, REPORTS <span class="op">/</span> <span class="st">"diccionario_datos.md"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Diccionario escrito en: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/reports/diccionario_datos.md</code></pre>
</div>
</div>
</section>
</section>
<section id="preparacion-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="preparacion-de-datos">2. Preparacion de datos</h2>
<p>Aqui mostramos <strong>como</strong> se obtuvo el dataset de trabajo a partir del dataset crudo de modelado, aplicando el <strong>patron de diseno Pipeline</strong>. Encadenamos pasos (cada uno una funcion <code>df -&gt; df</code>) en orden, registrando las filas antes y despues de cada paso en una <strong>bitacora auditable</strong>.</p>
<p>Partimos de <code>c5_modelado.parquet</code> (504,261 filas, <strong>antes</strong> de depurar: conserva <code>codigo_cierre</code> y todas las columnas).</p>
<div id="d48a21a0" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.324585Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.324530Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.368327Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.368118Z&quot;}}" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>crudo <span class="op">=</span> pd.read_parquet(DATA <span class="op">/</span> <span class="st">"c5_modelado.parquet"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Dataset de modelado (antes de depurar):"</span>, crudo.shape)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>crudo[[<span class="st">"folio"</span>, <span class="st">"codigo_cierre"</span>, <span class="st">"ANIO"</span>, <span class="st">"tipo_entrada"</span>]].head(<span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataset de modelado (antes de depurar): (504261, 18)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">folio</th>
<th data-quarto-table-cell-role="th">codigo_cierre</th>
<th data-quarto-table-cell-role="th">ANIO</th>
<th data-quarto-table-cell-role="th">tipo_entrada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>C2C/20211229/00212</td>
<td>I</td>
<td>2021</td>
<td>BOTÓN DE AUXILIO</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>C2C/20211231/00183</td>
<td>A</td>
<td>2021</td>
<td>BOTÓN DE AUXILIO</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>C2C/20220101/00012</td>
<td>A</td>
<td>2022</td>
<td>BOTÓN DE AUXILIO</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="analisis-de-codigo_cierre-por-que-eliminamos-los-duplicados" class="level3">
<h3 class="anchored" data-anchor-id="analisis-de-codigo_cierre-por-que-eliminamos-los-duplicados">2.1 Analisis de <code>codigo_cierre</code>: por que eliminamos los duplicados</h3>
<p>El target nace de <code>codigo_cierre</code>. Veamos su distribucion.</p>
<div id="b2e94b30" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.369425Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.369367Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.384073Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.383861Z&quot;}}" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>cc <span class="op">=</span> crudo[<span class="st">"codigo_cierre"</span>].value_counts(dropna<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>cc_pct <span class="op">=</span> (crudo[<span class="st">"codigo_cierre"</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>, dropna<span class="op">=</span><span class="va">False</span>) <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>tabla_cc <span class="op">=</span> pd.DataFrame({<span class="st">"conteo"</span>: cc, <span class="st">"porcentaje"</span>: cc_pct})</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>tabla_cc</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">conteo</th>
<th data-quarto-table-cell-role="th">porcentaje</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">codigo_cierre</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">D</th>
<td>214326</td>
<td>42.5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">A</th>
<td>184097</td>
<td>36.51</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">F</th>
<td>102230</td>
<td>20.27</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">I</th>
<td>3608</td>
<td>0.72</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Decision de diseno: los duplicados <code>D</code> se eliminan.</strong> La pregunta de negocio es <em>¿el reporte es real (afirmativo) o falso?</em>. Un cierre <strong><code>D</code> (Duplicado) es un evento REAL ya reportado</strong>: significa que alguien mas ya levanto ese mismo incidente. Detectar que un reporte entrante coincide con uno ya abierto es tarea del <strong>sistema de despacho</strong> (verificar si ya hay una unidad en el sitio), <strong>no</strong> del modelo de veracidad. Mezclar <code>D</code> en el target contaminaria la pregunta: estariamos pidiendo al modelo que prediga “novedad operativa” en vez de “veracidad”.</p>
<p>Por eso <strong>eliminamos</strong> los <code>D</code> (42.5%) y, entre el resto, definimos:</p>
<blockquote class="blockquote">
<p><code>REAL = 1</code> si <code>codigo_cierre == 'A'</code> (afirmativo) · <code>REAL = 0</code> si <code>F</code> (falso) o <code>I</code> (informativo).</p>
</blockquote>
<p><strong>Alternativa descartada.</strong> Si en cambio contaramos <code>D</code> como real (<code>REAL = 1</code> para <code>A</code> y <code>D</code>), el balance pasaria a <strong>~79/21</strong> a favor de la clase real: un desbalance mucho peor y, sobre todo, un <strong>target borroso</strong> que confunde veracidad con duplicidad. Preferimos un target limpio y un balance mas manejable (63.5/36.5).</p>
</section>
<section id="la-clase-pipelinepreparacion-y-los-pasos" class="level3">
<h3 class="anchored" data-anchor-id="la-clase-pipelinepreparacion-y-los-pasos">2.2 La clase <code>PipelinePreparacion</code> y los pasos</h3>
<p>La clase <code>PipelinePreparacion</code> y los pasos de limpieza viven en <code>src/preparacion.py</code>. Cada paso es una <strong>subclase</strong> de <code>PasoLimpieza</code> (<code>QuitarDuplicados</code>, <code>QuitarAnioRuido</code>, <code>ConstruirTarget</code>) con una unica responsabilidad (herencia); <code>PipelinePreparacion</code> los <strong>encadena</strong> (composicion) e imprime la bitacora. Aqui los importamos y aplicamos.</p>
<div id="17b165bc" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.385111Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.385046Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.386924Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.386777Z&quot;}}" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># La clase y los pasos se importan de src/preparacion.py (ver celda de</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># configuracion). pipeline_estandar() arma el pipeline del proyecto:</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   QuitarDuplicados -&gt; QuitarAnioRuido -&gt; ConstruirTarget</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.preparacion <span class="im">import</span> (PipelinePreparacion, QuitarDuplicados,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                             QuitarAnioRuido, ConstruirTarget, pipeline_estandar)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Pasos del pipeline:"</span>, [p.nombre <span class="cf">for</span> p <span class="kw">in</span> pipeline_estandar().pasos])</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pasos del pipeline: ['quitar_duplicados', 'quitar_anio_ruido', 'construir_target']</code></pre>
</div>
</div>
<div id="2b988141" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.387755Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.387711Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.451410Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.451183Z&quot;}}" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicamos el pipeline (definido en src/) y observamos la bitacora.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>pipeline <span class="op">=</span> pipeline_estandar()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Bitacora del pipeline de preparacion:"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>listo <span class="op">=</span> pipeline.aplicar(crudo)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Resultado final:"</span>, listo.shape)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Coincide con c5_listo.parquet (289,885 filas):"</span>, <span class="bu">len</span>(listo) <span class="op">==</span> <span class="dv">289885</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bitacora del pipeline de preparacion:
  quitar_duplicados             504,261 -&gt;  289,935
  quitar_anio_ruido             289,935 -&gt;  289,885
  construir_target              289,885 -&gt;  289,885

Resultado final: (289885, 18)
Coincide con c5_listo.parquet (289,885 filas): True</code></pre>
</div>
</div>
<p><strong>Interpretacion del patron Pipeline.</strong> La bitacora deja la trazabilidad completa: <strong>504,261 -&gt; 289,935 -&gt; 289,885</strong>.</p>
<p>El primer paso retira los 214,326 duplicados <code>D</code> el segundo elimina los 50 reportes de <strong>2021</strong> (ruido de frontera: unos cuantos reportes con fecha de diciembre-2021 que se colaron en el corte 2022-2024), el tercero construye el target binario <code>REAL</code>. Cada paso es una funcion pequeña y verificable, y agregar o quitar un paso es trivial. Por eso preferimos usar este patrón.</p>
<p>El resultado en memoria es <strong>identico</strong> al archivo <code>data/c5_listo.parquet</code> que ya cargamos en la seccion 1 (no reescribimos a disco). En adelante seguimos con ese dataset de trabajo de <strong>289,885 filas</strong>.</p>
<div id="08a32716" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.452422Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.452370Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.457312Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.457145Z&quot;}}" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confirmamos el balance del target sobre el dataset depurado.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>balance <span class="op">=</span> df[<span class="st">"REAL"</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>).sort_index()</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Balance del target REAL:"</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  0 (falso/informativo): </span><span class="sc">{</span>balance[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  1 (afirmativo/real)  : </span><span class="sc">{</span>balance[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Balance del target REAL:
  0 (falso/informativo): 0.365
  1 (afirmativo/real)  : 0.635</code></pre>
</div>
</div>
<p>Las funciones auxiliares de graficado (<code>barras</code>, <code>guardar</code>) y de estadistica (<code>resumen_numerico</code>) viven en <code>src/viz.py</code> y ya se importaron en la celda de configuracion.</p>
<div id="987e1167" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.458196Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.458152Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.459579Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.459404Z&quot;}}" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># `barras`, `guardar` y `resumen_numerico` se importan de src/viz.py</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (ver celda de configuracion). No se redefinen aqui.</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Helpers de graficado cargados desde src.viz"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Helpers de graficado cargados desde src.viz</code></pre>
</div>
</div>
</section>
<section id="calidad-de-los-datos-faltantes-y-duplicados" class="level3">
<h3 class="anchored" data-anchor-id="calidad-de-los-datos-faltantes-y-duplicados">3.1 Calidad de los datos: faltantes y duplicados</h3>
<div id="befeca37" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.460433Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.460390Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.573267Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.573059Z&quot;}}" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>na <span class="op">=</span> df.isna().<span class="bu">sum</span>()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>na <span class="op">=</span> na[na <span class="op">&gt;</span> <span class="dv">0</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>tabla_na <span class="op">=</span> pd.DataFrame({<span class="st">"faltantes"</span>: na, <span class="st">"porcentaje"</span>: (na <span class="op">/</span> <span class="bu">len</span>(df) <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">3</span>)})</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Faltantes por columna (solo columnas con algun nulo):"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabla_na.to_string())</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Filas exactamente duplicadas:"</span>, <span class="bu">int</span>(df.duplicated().<span class="bu">sum</span>()))</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Folios duplicados            :"</span>, <span class="bu">int</span>(df[<span class="st">"folio"</span>].duplicated().<span class="bu">sum</span>()))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Faltantes por columna (solo columnas con algun nulo):
                   faltantes  porcentaje
alcaldia_catalogo        366       0.126
tipo_entrada               3       0.001
TIEMPO_CIERRE_MIN          2       0.001

Filas exactamente duplicadas: 0
Folios duplicados            : 0</code></pre>
</div>
</div>
<p><strong>Interpretacion.</strong> El dataset esta muy limpio. Solo tres columnas tienen faltantes y todos son marginales. <code>alcaldia_catalogo</code> (366 nulos, 0.13%) y <code>tipo_entrada</code> (3 nulos) son reportes cuya ubicacion o canal no quedo registrado, y <code>TIEMPO_CIERRE_MIN</code> (2 nulos) no es feature del modelo. <strong>No hay folios repetidos ni filas identicas</strong>, coherente con que ya retiramos los duplicados <code>D</code>. Cada registro es un reporte único. Los nulos de <code>alcaldia_catalogo</code>/<code>tipo_entrada</code> los maneja el <code>ColumnTransformer</code> del notebook 02 con una categoria explicita, asi que no eliminamos filas aqui.</p>
</section>
<section id="estadistica-descriptiva-hora-y-tiempo_cierre_min" class="level3">
<h3 class="anchored" data-anchor-id="estadistica-descriptiva-hora-y-tiempo_cierre_min">3.2 Estadistica descriptiva: <code>HORA</code> y <code>TIEMPO_CIERRE_MIN</code></h3>
<p>Para las dos numericas mas interesantes reportamos media, mediana, desviacion, cuartiles, rango y forma (asimetria y curtosis con <code>scipy</code>).</p>
<div id="91c75fce" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.574279Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.574226Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.598653Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.598465Z&quot;}}" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># resumen_numerico viene de src/viz.py; aqui solo lo aplicamos.</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>resumen <span class="op">=</span> pd.DataFrame({</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"HORA"</span>: resumen_numerico(df[<span class="st">"HORA"</span>]),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"TIEMPO_CIERRE_MIN"</span>: resumen_numerico(df[<span class="st">"TIEMPO_CIERRE_MIN"</span>]),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>resumen</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">HORA</th>
<th data-quarto-table-cell-role="th">TIEMPO_CIERRE_MIN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">n</th>
<td>289885.000</td>
<td>289883.000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">media</th>
<td>13.850</td>
<td>296.862</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">mediana</th>
<td>15.000</td>
<td>188.783</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">std</th>
<td>6.084</td>
<td>340.365</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">min</th>
<td>0.000</td>
<td>0.317</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Q1</th>
<td>9.000</td>
<td>184.700</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Q3</th>
<td>19.000</td>
<td>225.800</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>23.000</td>
<td>4657.133</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">asimetria</th>
<td>-0.519</td>
<td>3.726</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">curtosis</th>
<td>-0.580</td>
<td>15.496</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Interpretacion.</strong> <code>HORA</code> es casi simetrica (asimetria ~ -0.52) y plana (curtosis negativa ~ -0.58): los reportes se reparten a lo largo del dia con una concentracion vespertina (mediana 15 h). En cambio <code>TIEMPO_CIERRE_MIN</code> esta <strong>fuertemente sesgada a la derecha</strong> (asimetria ~ 3.7) y tiene una cola extremadamente cargada a la <strong>derecha</strong> (curtosis ~ 15.5): mediana ~189 min pero con una cola larguisima hasta ~4,657 min.</p>
<p>Esta forma extrema es tipica de tiempos de servicio y, sumada a que solo se conoce <strong>al cerrar</strong> el reporte, refuerza que <code>TIEMPO_CIERRE_MIN</code> quede <strong>fuera del modelo</strong> (fuga); aqui la usamos solo como ilustracion de outliers.</p>
</section>
<section id="valores-atipicos-en-tiempo_cierre_min-boxplot-regla-iqr" class="level3">
<h3 class="anchored" data-anchor-id="valores-atipicos-en-tiempo_cierre_min-boxplot-regla-iqr">3.3 Valores atipicos en <code>TIEMPO_CIERRE_MIN</code> (boxplot + regla IQR)</h3>
<div id="b7c88b99" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.599715Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.599664Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:52.795925Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:52.795718Z&quot;}}" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> df[<span class="st">"TIEMPO_CIERRE_MIN"</span>].dropna().astype(<span class="st">"float64"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>Q1, Q3 <span class="op">=</span> t.quantile(<span class="fl">.25</span>), t.quantile(<span class="fl">.75</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>IQR <span class="op">=</span> Q3 <span class="op">-</span> Q1</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>lim_sup <span class="op">=</span> Q3 <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> IQR</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>n_out <span class="op">=</span> <span class="bu">int</span>((t <span class="op">&gt;</span> lim_sup).<span class="bu">sum</span>())</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Q1=</span><span class="sc">{</span>Q1<span class="sc">:.1f}</span><span class="ss">  Q3=</span><span class="sc">{</span>Q3<span class="sc">:.1f}</span><span class="ss">  IQR=</span><span class="sc">{</span>IQR<span class="sc">:.1f}</span><span class="ss">  limite superior=</span><span class="sc">{</span>lim_sup<span class="sc">:.1f}</span><span class="ss"> min"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Outliers (&gt; limite): </span><span class="sc">{</span>n_out<span class="sc">:,}</span><span class="ss">  (</span><span class="sc">{</span>n_out<span class="op">/</span><span class="bu">len</span>(t)<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%)"</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">4</span>))</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].boxplot(t, vert<span class="op">=</span><span class="va">True</span>, showfliers<span class="op">=</span><span class="va">True</span>, patch_artist<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>                boxprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">"lightcoral"</span>))</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"TIEMPO_CIERRE_MIN - boxplot (con outliers)"</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"minutos"</span>)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Zoom recortando la cola para ver la caja.</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].boxplot(t.clip(upper<span class="op">=</span>lim_sup <span class="op">*</span> <span class="fl">1.2</span>), vert<span class="op">=</span><span class="va">True</span>, patch_artist<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>                boxprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">"lightcoral"</span>))</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Zoom hasta ~1.2x el limite IQR"</span>)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"minutos"</span>)</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_outliers_tiempo_cierre.png"</span>)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Q1=184.7  Q3=225.8  IQR=41.1  limite superior=287.5 min
Outliers (&gt; limite): 49,211  (16.98%)
Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_outliers_tiempo_cierre.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-15-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>La regla IQR marca una fraccion notable de reportes con tiempos de cierre extremos (la cola a la derecha del boxplot). No los eliminamos, primero porque <code>TIEMPO_CIERRE_MIN</code> no es feature del modelo y segundo, esos tiempos largos son <strong>reales</strong> (reportes complejos que tardan en cerrarse), no errores de captura. Podríamos imaginarnos que en casos donde hubo casualidades la resolución del caso sea más compleja que por ejemplo un choque ligero. El zoom confirma que el grueso de la distribucion vive alrededor de ~3 horas, con una cola operativa larga pero legitima.</p>
</section>
<section id="distribuciones-hora-franja-y-dia_semana" class="level3">
<h3 class="anchored" data-anchor-id="distribuciones-hora-franja-y-dia_semana">3.4 Distribuciones: <code>HORA</code>, <code>FRANJA</code> y <code>dia_semana</code></h3>
<div id="72d61201" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:52.797062Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:52.797008Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:53.033002Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:53.032765Z&quot;}}" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">4</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma de HORA con media y mediana.</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].hist(df[<span class="st">"HORA"</span>].astype(<span class="st">"float64"</span>), bins<span class="op">=</span><span class="dv">24</span>, color<span class="op">=</span><span class="st">"steelblue"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>             edgecolor<span class="op">=</span><span class="st">"black"</span>, linewidth<span class="op">=</span><span class="fl">.4</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(df[<span class="st">"HORA"</span>].mean(), color<span class="op">=</span><span class="st">"red"</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="ss">f"media </span><span class="sc">{</span>df[<span class="st">'HORA'</span>]<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(df[<span class="st">"HORA"</span>].median(), color<span class="op">=</span><span class="st">"green"</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="ss">f"mediana </span><span class="sc">{</span>df[<span class="st">'HORA'</span>]<span class="sc">.</span>median()<span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Distribucion de HORA"</span>)<span class="op">;</span> axes[<span class="dv">0</span>].set_xlabel(<span class="st">"hora del dia"</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"conteo"</span>)<span class="op">;</span> axes[<span class="dv">0</span>].legend()</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Barras de FRANJA (orden natural del dia).</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>orden_franja <span class="op">=</span> [<span class="st">"Madrugada"</span>, <span class="st">"Mañana"</span>, <span class="st">"Tarde"</span>, <span class="st">"Noche"</span>]</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>fr <span class="op">=</span> df[<span class="st">"FRANJA"</span>].value_counts().reindex(orden_franja)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>barras(fr, <span class="st">"Reportes por FRANJA horaria"</span>, <span class="st">"franja"</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>], color<span class="op">=</span><span class="st">"darkorange"</span>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Barras de dia_semana (orden natural).</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>orden_dia <span class="op">=</span> [<span class="st">"Lunes"</span>, <span class="st">"Martes"</span>, <span class="st">"Miércoles"</span>, <span class="st">"Jueves"</span>, <span class="st">"Viernes"</span>, <span class="st">"Sábado"</span>, <span class="st">"Domingo"</span>]</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>ds <span class="op">=</span> df[<span class="st">"dia_semana"</span>].value_counts().reindex(orden_dia)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>barras(ds, <span class="st">"Reportes por dia de la semana"</span>, <span class="st">"dia"</span>, ax<span class="op">=</span>axes[<span class="dv">2</span>], color<span class="op">=</span><span class="st">"seagreen"</span>, rot<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_distribuciones.png"</span>)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_distribuciones.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-16-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretacion.</strong> En <code>HORA</code> hay pocos reportes de madrugada (3-6 h), ascenso a lo largo de la mañana y un grueso concentrado de la tarde a la noche, con la mediana en las 15 h. Eso se refleja en <code>FRANJA</code>: <strong>Tarde</strong> y <strong>Noche</strong> acumulan el mayor volumen y la <strong>Madrugada</strong> es la franja mas vacia, siguiendo el ritmo de la actividad vial de la ciudad. Por dia de la semana destacan <strong>viernes y sabado</strong> (mayor movilidad y vida nocturna), mientras el lunes es el más tranquilo. Son patrones plausibles y utiles como señal temporal moderada para el modelo.</p>
</section>
<section id="balance-del-target-real-decision-de-diseno" class="level3">
<h3 class="anchored" data-anchor-id="balance-del-target-real-decision-de-diseno">3.5 Balance del target <code>REAL</code> (decision de diseno)</h3>
<div id="b09ed406" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:53.034092Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:53.034039Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:53.097553Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:53.097351Z&quot;}}" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>vc <span class="op">=</span> df[<span class="st">"REAL"</span>].value_counts().sort_index()</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>prop <span class="op">=</span> df[<span class="st">"REAL"</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>).sort_index()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="fl">4.2</span>))</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>colores <span class="op">=</span> [<span class="st">"indianred"</span>, <span class="st">"seagreen"</span>]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.bar([<span class="st">"0 - falso/informativo"</span>, <span class="st">"1 - afirmativo (real)"</span>], vc.values,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>              color<span class="op">=</span>colores, edgecolor<span class="op">=</span><span class="st">"black"</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b, p <span class="kw">in</span> <span class="bu">zip</span>(bars, prop.values):</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    ax.text(b.get_x() <span class="op">+</span> b.get_width()<span class="op">/</span><span class="dv">2</span>, b.get_height(),</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f"</span><span class="sc">{</span>p<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>, ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"bottom"</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Balance del target REAL (n = 289,885)"</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"conteo"</span>)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_balance_target.png"</span>)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Razon de desbalance (real : no real):"</span>, <span class="bu">round</span>(prop[<span class="dv">1</span>] <span class="op">/</span> prop[<span class="dv">0</span>], <span class="dv">2</span>), <span class="st">": 1"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_balance_target.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-17-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Razon de desbalance (real : no real): 1.74 : 1</code></pre>
</div>
</div>
<p>Tras quitar los duplicados, <strong>63.5%</strong> de los reportes son reales (<code>A</code>) y <strong>36.5%</strong> son falsos/informativos (<code>F</code>/<code>I</code>). Hay un desbalance <strong>moderado</strong> (~1.74 : 1) a favor de la clase real. Esto significa que:</p>
<blockquote class="blockquote">
<p>La metrica rectora sera <strong>F1 macro</strong>, porque la <em>accuracy</em> podría ser alcanzada casi un clasificador trivial que diga “real” a todo Se usara <code>class_weight='balanced'</code> para no sacrificar el recall de la clase <strong>no real</strong> (filtrar falsos es justo el valor de negocio).</p>
</blockquote>
<p><strong>Nota:</strong> este balance limpio (63.5/36.5) es preferible al ~79/21 que daria contar los duplicados como reales, como argumentamos en la seccion 2.</p>
</section>
<section id="correlaciones-entre-numericas-y-dispersion-espacial" class="level3">
<h3 class="anchored" data-anchor-id="correlaciones-entre-numericas-y-dispersion-espacial">3.6 Correlaciones entre numericas y dispersion espacial</h3>
<p>La rubrica pide una <strong>matriz de correlaciones</strong> y <strong>scatter plots</strong> de pares relevantes. Como el problema tiene pocas numericas, calculamos la correlacion de <strong>Spearman</strong> (monotona, robusta a no-linealidad) entre ellas y con el target, y visualizamos un par espacial relevante (longitud vs latitud) coloreado por <code>REAL</code>.</p>
<div id="432c4de0" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:53.098611Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:53.098553Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:53.517390Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:53.517175Z&quot;}}" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Matriz de correlacion de Spearman: numericas + el target.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>num_corr <span class="op">=</span> [<span class="st">"HORA"</span>, <span class="st">"MES"</span>, <span class="st">"ANIO"</span>, <span class="st">"latitud"</span>, <span class="st">"longitud"</span>, <span class="st">"TIEMPO_CIERRE_MIN"</span>, <span class="st">"REAL"</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>corr <span class="op">=</span> df[num_corr].astype(<span class="st">"float64"</span>).corr(method<span class="op">=</span><span class="st">"spearman"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">5.6</span>))</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>sns.heatmap(corr, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">".2f"</span>, cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, center<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>            vmin<span class="op">=-</span><span class="dv">1</span>, vmax<span class="op">=</span><span class="dv">1</span>, square<span class="op">=</span><span class="va">True</span>, linewidths<span class="op">=</span><span class="fl">.5</span>, ax<span class="op">=</span>ax,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>            cbar_kws<span class="op">=</span>{<span class="st">"shrink"</span>: <span class="fl">.8</span>})</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Correlacion de Spearman (numericas + target REAL)"</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_correlacion.png"</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_correlacion.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-18-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretacion.</strong> Las variables numericas estan <strong>practicamente descorrelacionadas entre si</strong> (|r| &lt; 0.1, salvo un leve MES-ANIO de -0.21 por el corte temporal) y, sobre todo, su correlacion con el target <code>REAL</code> es <strong>muy baja</strong>: la mayor entre las <em>features del modelo</em> es <code>latitud</code> (0.08), seguida de <code>HORA</code> (-0.07). El unico valor apreciable, <code>TIEMPO_CIERRE_MIN</code> (0.26), proviene de una variable de <strong>fuga</strong> (excluida del modelo). La lectura clave es que las numericas aportan <strong>poca senal monotona</strong> sobre la veracidad; el poder predictivo vendra de las <strong>categoricas</strong> (canal, tipo de incidente), justo lo que confirmara la importancia por permutacion del notebook 02.</p>
<div id="1f711efe" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:53.518421Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:53.518366Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:53.708124Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:53.707924Z&quot;}}" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter de un par espacial relevante: longitud vs latitud por veracidad.</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> df.sample(n<span class="op">=</span><span class="dv">8000</span>, random_state<span class="op">=</span>SEMILLA)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">5.6</span>))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>sc <span class="op">=</span> ax.scatter(m[<span class="st">"longitud"</span>].astype(<span class="st">"float64"</span>), m[<span class="st">"latitud"</span>].astype(<span class="st">"float64"</span>),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                c<span class="op">=</span>m[<span class="st">"REAL"</span>], cmap<span class="op">=</span><span class="st">"coolwarm"</span>, s<span class="op">=</span><span class="dv">7</span>, alpha<span class="op">=</span><span class="fl">.5</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"longitud"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"latitud"</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>ax.set_aspect(<span class="st">"equal"</span>, adjustable<span class="op">=</span><span class="st">"datalim"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Ubicacion de incidentes coloreada por REAL (muestra 8,000)"</span>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>fig.colorbar(sc, ax<span class="op">=</span>ax, label<span class="op">=</span><span class="st">"REAL (0 = falso/inform., 1 = real)"</span>, shrink<span class="op">=</span><span class="fl">.8</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_scatter_geo.png"</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_scatter_geo.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-19-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretacion.</strong> En el scatter espacial los reportes reales y los falsos/informativos <strong>se entremezclan por toda la ciudad</strong>: no hay una frontera geografica nitida que los separe, coherente con la baja correlacion de <code>latitud</code>/<code>longitud</code> con el target. Existe estructura espacial (mas densidad en el centro-oriente), pero es <strong>sutil</strong> y no separable de forma lineal simple; sera el <strong>clustering espacial del notebook 03</strong> (DBSCAN) el que la explote para hallar corredores de incidentes.</p>
</section>
</section>
<section id="geografia-del-reporte-quien-reporta-donde-y-que-tan-confiable-es" class="level2">
<h2 class="anchored" data-anchor-id="geografia-del-reporte-quien-reporta-donde-y-que-tan-confiable-es">4. Geografia del reporte: ¿quien reporta, donde y que tan confiable es?</h2>
<p>La pregunta de negocio central del EDA: <strong>¿que canal de entrada es mas confiable</strong>, y <strong>como se mezcla con la alcaldia</strong>? Esta seccion cuenta esa historia.</p>
<section id="confiabilidad-por-canal-de-entrada-tipo_entrada" class="level3">
<h3 class="anchored" data-anchor-id="confiabilidad-por-canal-de-entrada-tipo_entrada">4.1 Confiabilidad por canal de entrada (<code>tipo_entrada</code>)</h3>
<p>Para cada canal calculamos su <strong>volumen</strong> y su <strong>tasa de confirmacion</strong> (% de reportes con <code>REAL = 1</code>).</p>
<div id="549889ca" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:53.709221Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:53.709157Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:53.801842Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:53.801642Z&quot;}}" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> (df.groupby(<span class="st">"tipo_entrada"</span>, observed<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>        .agg(n<span class="op">=</span>(<span class="st">"REAL"</span>, <span class="st">"size"</span>), pct_real<span class="op">=</span>(<span class="st">"REAL"</span>, <span class="st">"mean"</span>)))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"pct_real"</span>] <span class="op">=</span> (g[<span class="st">"pct_real"</span>] <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"pct_volumen"</span>] <span class="op">=</span> (g[<span class="st">"n"</span>] <span class="op">/</span> <span class="bu">len</span>(df) <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> g.sort_values(<span class="st">"n"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(g[[<span class="st">"n"</span>, <span class="st">"pct_volumen"</span>, <span class="st">"pct_real"</span>]].to_string())</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Solo canales con volumen suficiente para una tasa estable (n &gt;= 100).</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>g_plot <span class="op">=</span> g[g[<span class="st">"n"</span>] <span class="op">&gt;=</span> <span class="dv">100</span>].sort_values(<span class="st">"pct_real"</span>)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">8.5</span>, <span class="fl">4.5</span>))</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.barh(g_plot.index, g_plot[<span class="st">"pct_real"</span>], color<span class="op">=</span><span class="st">"teal"</span>, edgecolor<span class="op">=</span><span class="st">"black"</span>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>ax.axvline(df[<span class="st">"REAL"</span>].mean() <span class="op">*</span> <span class="dv">100</span>, color<span class="op">=</span><span class="st">"red"</span>, ls<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"media global </span><span class="sc">{</span>df[<span class="st">'REAL'</span>]<span class="sc">.</span>mean()<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b, v <span class="kw">in</span> <span class="bu">zip</span>(bars, g_plot[<span class="st">"pct_real"</span>]):</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>    ax.text(b.get_width() <span class="op">+</span> <span class="fl">.5</span>, b.get_y() <span class="op">+</span> b.get_height()<span class="op">/</span><span class="dv">2</span>, <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.0f}</span><span class="ss">%"</span>,</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>            va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"</span><span class="sc">% d</span><span class="st">e reportes reales por canal de entrada"</span>)</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"</span><span class="sc">% r</span><span class="st">eal (REAL = 1)"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_fuente_confirmacion.png"</span>)</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       n  pct_volumen  pct_real
tipo_entrada                                   
LLAMADA DEL 911   253917        87.59      59.8
RADIO              19541         6.74      93.3
BOTÓN DE AUXILIO   14256         4.92      88.4
CÁMARA              1188         0.41      92.9
APLICATIVOS          504         0.17      28.4
REDES                438         0.15      53.9
LLAMADA APP911        35         0.01      48.6
SOS MUJERES *765       2         0.00     100.0
LECTOR DE PLACAS       1         0.00     100.0
Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_fuente_confirmacion.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-20-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>El <strong>canal es muy informativo</strong>. Los reportes que entran por canales <strong>institucionales</strong> operados por personal del C5 son casi siempre reales: <strong>RADIO ~93%</strong>, <strong>CAMARA ~93%</strong> y <strong>BOTON DE AUXILIO ~88%</strong>. En cambio la <strong>LLAMADA DEL 911</strong>, que es el <strong>~88% del volumen</strong>, confirma solo <strong>~60%</strong>, justo por debajo de la media global. Los aplicativos ciudadanos son los menos confiables (<strong>APLICATIVOS ~28%</strong>). Implicacion operativa directa: se puede despachar de manera casi automatica con <strong>alta prioridad</strong> lo que entra por canales institucionales y aplicar mas escrutinio a la avalancha de llamadas ciudadanas, que es donde se concentra la ambiguedad. La fuente será el predictor más informativo del modelo.</p>
</section>
<section id="confiabilidad-por-alcaldia" class="level3">
<h3 class="anchored" data-anchor-id="confiabilidad-por-alcaldia">4.2 Confiabilidad por alcaldia</h3>
<div id="6979c61a" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:53.802870Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:53.802809Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:53.925539Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:53.925254Z&quot;}}" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> (df.groupby(<span class="st">"alcaldia_catalogo"</span>, observed<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>        .agg(n<span class="op">=</span>(<span class="st">"REAL"</span>, <span class="st">"size"</span>), pct_real<span class="op">=</span>(<span class="st">"REAL"</span>, <span class="st">"mean"</span>)))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>a[<span class="st">"pct_real"</span>] <span class="op">=</span> (a[<span class="st">"pct_real"</span>] <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> a.sort_values(<span class="st">"pct_real"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">8.5</span>, <span class="dv">5</span>))</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>ax.barh(a.index[::<span class="op">-</span><span class="dv">1</span>], a[<span class="st">"pct_real"</span>][::<span class="op">-</span><span class="dv">1</span>], color<span class="op">=</span><span class="st">"slateblue"</span>, edgecolor<span class="op">=</span><span class="st">"black"</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>ax.axvline(df[<span class="st">"REAL"</span>].mean() <span class="op">*</span> <span class="dv">100</span>, color<span class="op">=</span><span class="st">"red"</span>, ls<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"media global </span><span class="sc">{</span>df[<span class="st">'REAL'</span>]<span class="sc">.</span>mean()<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"</span><span class="sc">% d</span><span class="st">e reportes reales por alcaldia"</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"</span><span class="sc">% r</span><span class="st">eal (REAL = 1)"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_alcaldia_confirmacion.png"</span>)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(a[[<span class="st">"n"</span>, <span class="st">"pct_real"</span>]].to_string())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_alcaldia_confirmacion.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-21-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                            n  pct_real
alcaldia_catalogo                      
Cuauhtémoc              32074      75.3
Azcapotzalco            11568      72.4
Venustiano Carranza     21061      67.1
Benito Juárez           20303      66.9
Coyoacán                20336      65.3
Miguel Hidalgo          19725      64.8
Gustavo A. Madero       31421      64.7
Tláhuac                  8870      63.9
Iztacalco               13242      59.5
Iztapalapa              46680      59.0
Tlalpan                 20370      58.6
Álvaro Obregón          19885      58.5
Milpa Alta               2270      56.1
La Magdalena Contreras   4619      55.8
Xochimilco              11202      51.8
Cuajimalpa de Morelos    5893      50.7</code></pre>
</div>
</div>
<p>Hay heterogeneidad geografica. El ranking va de <strong>Cuauhtemoc (~75%)</strong> y <strong>Azcapotzalco (~72%)</strong> hasta <strong>Cuajimalpa (~51%)</strong> y <strong>Xochimilco (~52%)</strong>, un rango de <strong>~25 puntos</strong>. Las alcaldias centrales con mas camaras, operadores y trafico verificable tienden a mayor tasa de confirmación que la periferia. La diferencia es real pero <strong>menor que la diferencia por canal</strong> (RADIO ~93% vs 911 ~60% son ~33 puntos): la geografia aporta señal <strong>complementaria</strong>, que el clustering del notebook 03 explotara como <em>hotspots</em>.</p>
</section>
<section id="mezcla-canal-x-alcaldia-heatmap-y-prueba-de-independencia" class="level3">
<h3 class="anchored" data-anchor-id="mezcla-canal-x-alcaldia-heatmap-y-prueba-de-independencia">4.3 Mezcla canal x alcaldia: heatmap y prueba de independencia</h3>
<p>¿La mezcla de canales cambia entre alcaldias? Construimos la tabla de contingencia, la mostramos como heatmap (en % por alcaldia, <strong>excluyendo la LLAMADA DEL 911</strong> que aplastaria la escala con ~88%) y medimos la asociacion con <strong>chi-cuadrado</strong> y la <strong>V de Cramer</strong>.</p>
<div id="d5749a33" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:53.926828Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:53.926756Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:54.118861Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:54.118663Z&quot;}}" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla de contingencia completa (conteos) para el test.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>ct <span class="op">=</span> pd.crosstab(df[<span class="st">"alcaldia_catalogo"</span>], df[<span class="st">"tipo_entrada"</span>])</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>chi2, p, dof, _ <span class="op">=</span> stats.chi2_contingency(ct)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> ct.values.<span class="bu">sum</span>()</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>cramer <span class="op">=</span> np.sqrt((chi2 <span class="op">/</span> n) <span class="op">/</span> (<span class="bu">min</span>(ct.shape) <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"chi2 = </span><span class="sc">{</span>chi2<span class="sc">:,.1f}</span><span class="ss">   p-value = </span><span class="sc">{</span>p<span class="sc">:.3g}</span><span class="ss">   dof = </span><span class="sc">{</span>dof<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"V de Cramer = </span><span class="sc">{</span>cramer<span class="sc">:.4f}</span><span class="ss">  (efecto pequeno &lt; 0.10)"</span>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Heatmap: % de cada canal dentro de la alcaldia, SIN la LLAMADA DEL 911.</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>mezcla <span class="op">=</span> ct.div(ct.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>), axis<span class="op">=</span><span class="dv">0</span>) <span class="op">*</span> <span class="dv">100</span>  <span class="co"># % sobre el total de la alcaldia</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>mezcla <span class="op">=</span> mezcla.loc[ct.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>).sort_values(ascending<span class="op">=</span><span class="va">False</span>).index]</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Solo canales (sin 911) con presencia apreciable para un heatmap legible.</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>canales_vis <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> mezcla.columns <span class="cf">if</span> c <span class="op">!=</span> <span class="st">"LLAMADA DEL 911"</span>]</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>canales_vis <span class="op">=</span> mezcla[canales_vis].<span class="bu">sum</span>().sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">5</span>).index</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">8.5</span>, <span class="dv">6</span>))</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>sns.heatmap(mezcla[canales_vis], annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">".1f"</span>, cmap<span class="op">=</span><span class="st">"YlOrRd"</span>,</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>            cbar_kws<span class="op">=</span>{<span class="st">"label"</span>: <span class="st">"</span><span class="sc">% d</span><span class="st">e reportes de la alcaldia"</span>}, ax<span class="op">=</span>ax)</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Mezcla de canales por alcaldia (</span><span class="sc">% s</span><span class="st">in LLAMADA DEL 911)"</span>)</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"canal"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"alcaldia"</span>)</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_mezcla_canal_alcaldia.png"</span>)</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>chi2 = 3,719.8   p-value = 0   dof = 120
V de Cramer = 0.0401  (efecto pequeno &lt; 0.10)
Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_mezcla_canal_alcaldia.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-22-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>El p-value es <strong>~0</strong> (rechazo de independencia), es decir, la alcaldia y el canal <strong>no</strong> son independientes. Pero con <strong>n ~ 290k casi cualquier asociacion sale “significativa”</strong>, asi que lo que importa es el <strong>tamano de efecto</strong>: la <strong>V de Cramer ~ 0.04</strong> es muy pequeña. Es decir, <em>si existe</em> relacion entre donde ocurre el reporte y por que canal entra, la <strong>CAMARA</strong> pesa más en alcaldias centrales como Cuauhtemoc, y el <strong>BOTON DE AUXILIO</strong> comunitario pesa mas en la periferia (Milpa Alta, Tlahuac), pero es <strong>debil en lo global</strong>, porque el dominio aplastante de la LLAMADA DEL 911 (~88% en todas) homogeneiza la mezcla. La geografia modula los canales minoritarios pero no reescribe el patrón dominante.</p>
</section>
<section id="canal-x-franja-horaria" class="level3">
<h3 class="anchored" data-anchor-id="canal-x-franja-horaria">4.4 Canal x franja horaria</h3>
<p>¿En que momento del dia reporta cada canal? Normalizamos <strong>por fila</strong> (perfil horario de cada canal) para que el volumen del 911 no aplaste la lectura.</p>
<div id="0cb152e8" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:54.119962Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:54.119910Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:54.233632Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:54.233442Z&quot;}}" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>orden_franja <span class="op">=</span> [<span class="st">"Madrugada"</span>, <span class="st">"Mañana"</span>, <span class="st">"Tarde"</span>, <span class="st">"Noche"</span>]</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>mf <span class="op">=</span> pd.crosstab(df[<span class="st">"tipo_entrada"</span>], df[<span class="st">"FRANJA"</span>]).reindex(columns<span class="op">=</span>orden_franja)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Solo canales con volumen suficiente.</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>mf <span class="op">=</span> mf[mf.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">&gt;=</span> <span class="dv">100</span>]</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>perfil <span class="op">=</span> mf.div(mf.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>), axis<span class="op">=</span><span class="dv">0</span>) <span class="op">*</span> <span class="dv">100</span>  <span class="co"># % por canal</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">8.5</span>, <span class="fl">4.5</span>))</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>sns.heatmap(perfil, annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">".0f"</span>, cmap<span class="op">=</span><span class="st">"Blues"</span>,</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>            cbar_kws<span class="op">=</span>{<span class="st">"label"</span>: <span class="st">"</span><span class="sc">% d</span><span class="st">e los reportes del canal"</span>}, ax<span class="op">=</span>ax)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Perfil horario por canal (% por fila)"</span>)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"franja"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"canal"</span>)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_canal_franja.png"</span>)</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_canal_franja.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-23-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>La <strong>CAMARA</strong> y la <strong>RADIO</strong> tienen el perfil <strong>mas plano y mas diurno</strong>, con una proporcion relativamente alta en <strong>madrugada-manana</strong>. La <strong>llamada ciudadana</strong> y el <strong>boton de auxilio</strong> se concentran en <strong>tarde-noche</strong>, siguiendo el ritmo de la actividad humana. En otras palabras: <strong>en las horas valle (madrugada) la vigilancia institucional sostiene una proporcion mayor del reporte</strong>, justo cuando hay menos ciudadanos despiertos para llamar, y como esos canales confirman ~90%, la madrugada hereda parte de su alta confiabilidad (coherente con que la franja Madrugada tenga la mayor tasa de % real).</p>
</section>
<section id="confiabilidad-por-franja-horaria" class="level3">
<h3 class="anchored" data-anchor-id="confiabilidad-por-franja-horaria">4.5 Confiabilidad por franja horaria</h3>
<p>Cerramos la geografía del reporte mirando la dimensión <strong>temporal de la confiabilidad</strong>: ¿la proporción de reportes reales cambia según la franja horaria (Madrugada / Mañana / Tarde / Noche)? A diferencia de la sección 4.4 —que describía <em>qué canal</em> domina en cada franja—, aquí medimos directamente la <strong>tasa de veracidad</strong> (<code>% REAL</code>) por franja.</p>
<div id="946aab53" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-06-10T11:19:54.234754Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-06-10T11:19:54.234693Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-06-10T11:19:54.320223Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-06-10T11:19:54.320021Z&quot;}}" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confiabilidad (% de reportes reales) por franja horaria.</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>orden_franja <span class="op">=</span> [<span class="st">"Madrugada"</span>, <span class="st">"Mañana"</span>, <span class="st">"Tarde"</span>, <span class="st">"Noche"</span>]</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> (df.groupby(<span class="st">"FRANJA"</span>, observed<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>        .agg(n<span class="op">=</span>(<span class="st">"REAL"</span>, <span class="st">"size"</span>), pct_real<span class="op">=</span>(<span class="st">"REAL"</span>, <span class="st">"mean"</span>)))</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>f[<span class="st">"pct_real"</span>] <span class="op">=</span> (f[<span class="st">"pct_real"</span>] <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>f[<span class="st">"pct_volumen"</span>] <span class="op">=</span> (f[<span class="st">"n"</span>] <span class="op">/</span> <span class="bu">len</span>(df) <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> f.reindex(orden_franja)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(f[[<span class="st">"n"</span>, <span class="st">"pct_volumen"</span>, <span class="st">"pct_real"</span>]].to_string())</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.5</span>, <span class="dv">4</span>))</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.bar(f.index, f[<span class="st">"pct_real"</span>], color<span class="op">=</span><span class="st">"darkorange"</span>, edgecolor<span class="op">=</span><span class="st">"black"</span>)</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>ax.axhline(df[<span class="st">"REAL"</span>].mean() <span class="op">*</span> <span class="dv">100</span>, color<span class="op">=</span><span class="st">"red"</span>, ls<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"media global </span><span class="sc">{</span>df[<span class="st">'REAL'</span>]<span class="sc">.</span>mean()<span class="op">*</span><span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>)</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b, v <span class="kw">in</span> <span class="bu">zip</span>(bars, f[<span class="st">"pct_real"</span>]):</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>    ax.text(b.get_x() <span class="op">+</span> b.get_width()<span class="op">/</span><span class="dv">2</span>, b.get_height() <span class="op">+</span> <span class="fl">.4</span>, <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.1f}</span><span class="ss">%"</span>,</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>            ha<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"</span><span class="sc">% d</span><span class="st">e reportes reales por franja horaria"</span>)</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"franja horaria"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"</span><span class="sc">% r</span><span class="st">eal (REAL = 1)"</span>)</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">80</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>guardar(fig, <span class="st">"01_franja_confirmacion.png"</span>)</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               n  pct_volumen  pct_real
FRANJA                                 
Madrugada  30563         10.5      70.1
Mañana     66177         22.8      68.3
Tarde      95820         33.1      61.5
Noche      97325         33.6      60.1
Figura guardada: /Users/rou/Desktop/8voSemestre/Almacenes/finalProyectoAyM/figures/01_franja_confirmacion.png</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_eda_files/figure-html/cell-24-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>La confiabilidad <strong>decae a lo largo del día</strong>. Los reportes de <strong>madrugada (70.1%)</strong> y <strong>mañana (68.3%)</strong> superan claramente la media global (63.5%), mientras que los de <strong>tarde (61.5%)</strong> y <strong>noche (60.1%)</strong> quedan por debajo. Hay una brecha de <strong>10 puntos</strong> entre la franja más confiable y la menos confiable. El detalle operativo es que tarde y noche concentran además <strong>el mayor volumen</strong> (33.1% y 33.6% de los reportes), es decir, las horas con más reportes son justamente las de menor proporción de incidentes reales y de madrugada llegan pocos reportes pero casi todos genuinos, mientras que en la noche el sistema recibe muchos reportes y una fracción mayor resulta falsa o informativa. La franja horaria aporta así una señal modesta pero coherente para la clasificación, complementaria a la del canal de entrada (sección 4.1).</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Proyecto Final — Almacenes y Minería de Datos · Facultad de Ciencias, UNAM · 2026</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>